CONFLUENCE_DATA_DIR: /Users/darrieythorsson/compHydro/data/CONFLUENCE_data
CONFLUENCE_CODE_DIR: /Users/darrieythorsson/compHydro/code/CONFLUENCE
DOMAIN_NAME: Iceland
EXPERIMENT_ID: regional
EXPERIMENT_TIME_START: 2011-01-01 01:00
EXPERIMENT_TIME_END: 2013-12-31 23:00
CALIBRATION_PERIOD: 2013-01-01, 2016-12-31
EVALUATION_PERIOD: 2017-01-01, 2022-12-31
SPINUP_PERIOD: 2011-01-01, 2012-12-31
MPI_PROCESSES: 1
FORCE_RUN_ALL_STEPS: false
POUR_POINT_COORDS: 64.01/-16.01
BOUNDING_BOX_COORDS: 66.8/-25.5/63.0/-13.0
POUR_POINT_SHP_PATH: default
POUR_POINT_SHP_NAME: default
DOMAIN_DEFINITION_METHOD: delineate
GEOFABRIC_TYPE: TDX
STREAM_THRESHOLD: 5000
LUMPED_WATERSHED_METHOD: pysheds
CLEANUP_INTERMEDIATE_FILES: true
DELINEATE_BY_POURPOINT: false
DELINEATE_COASTAL_WATERSHEDS: true
MIN_GRU_SIZE: 0
DOMAIN_DISCRETIZATION: GRUs
ELEVATION_BAND_SIZE: 400
MIN_HRU_SIZE: 5
RADIATION_CLASS_NUMBER: 5
CATCHMENT_PATH: default
CATCHMENT_SHP_NAME: default
CATCHMENT_SHP_LAT: center_lat
CATCHMENT_SHP_LON: center_lon
CATCHMENT_SHP_AREA: HRU_area
CATCHMENT_SHP_HRUID: HRU_ID
CATCHMENT_SHP_GRUID: GRU_ID
RIVER_BASINS_PATH: default
RIVER_BASINS_NAME: default
RIVER_BASIN_SHP_RM_GRUID: GRU_ID
RIVER_BASIN_SHP_HRU_TO_SEG: gru_to_seg
RIVER_BASIN_SHP_AREA: GRU_area
RIVER_NETWORK_SHP_PATH: default
RIVER_NETWORK_SHP_NAME: default
RIVER_NETWORK_SHP_LENGTH: Length
RIVER_NETWORK_SHP_SEGID: LINKNO
RIVER_NETWORK_SHP_DOWNSEGID: DSLINKNO
RIVER_NETWORK_SHP_SLOPE: Slope
OUTPUT_BASINS_PATH: default
OUTPUT_RIVERS_PATH: default
DEM_PATH: default
DEM_NAME: default
SOURCE_GEOFABRIC_BASINS_PATH: default
SOURCE_GEOFABRIC_RIVERS_PATH: defult
TAUDEM_DIR: default
OUTPUT_DIR: default
CATCHMENT_PLOT_DIR: default
SOIL_CLASS_PATH: default
SOIL_CLASS_NAME: default
LAND_CLASS_PATH: default
LAND_CLASS_NAME: default
RADIATION_PATH: default
DATATOOL_PATH: default
GISTOOL_PATH: default
EASYMORE_CLIENT: easymore cli
DATATOOL_DATASET_ROOT: /anvil/datasets/meteorological/
DATATOOL_CACHE: /home/x-deythorsson/
TOOL_ACCOUNT: def-mclark
GISTOOL_DATASET_ROOT: /anvil/datasets/geospatial/
GISTOOL_LIB_PATH: /work/comphyd_lab/envs/r-env/
TOOL_CACHE: /anvil/projects/x-ees240082/data/CONFLUENCE_data/cache/
EASYMORE_CACHE: /home/x-deythorsson/easymore/
EASYMORE_JOB_CONF: installs/MAF/02_model_agnostic_component/easymore-job.slurm
CLUSTER_JSON: /home/x-deythorsson/data/CONFLUENCE_data/installs/datatool/etc/clusters/perdue-anvil.json
DATA_ACQUIRE: HPC
FORCING_DATASET: ERA5
FORCING_VARIABLES: default
FORCING_MEASUREMENT_HEIGHT: 1.5
FORCING_TIME_STEP_SIZE: 3600
APPLY_LAPSE_RATE: true
LAPSE_RATE: 0.0065
FORCING_SHAPE_LAT_NAME: lat
FORCING_SHAPE_LON_NAME: lon
FORCING_PATH: default
SUPPLEMENT_FORCING: true
EM_EARTH_PRCP_DIR: /anvil/datasets/meteorological/EM-Earth/EM_Earth_v1/deterministic_hourly/prcp/NorthAmerica
EM_EARTH_TMEAN_DIR: /anvil/datasets/meteorological/EM-Earth/EM_Earth_v1/deterministic_hourly/tmean/NorthAmerica
EM_PRCP: prcp_corrected
INTERSECT_SOIL_PATH: default
INTERSECT_SOIL_NAME: catchment_with_soilclass.shp
INTERSECT_ROUTING_PATH: default
INTERSECT_ROUTING_NAME: catchment_with_routing_basins.shp
INTERSECT_DEM_PATH: default
INTERSECT_DEM_NAME: catchment_with_dem.shp
INTERSECT_LAND_PATH: default
INTERSECT_LAND_NAME: catchment_with_landclass.shp
HYDROLOGICAL_MODEL: SUMMA
ROUTING_MODEL: mizuRoute
SETTINGS_SUMMA_CONNECT_HRUS: true
SETTINGS_SUMMA_TRIALPARAM_N: 1
SETTINGS_SUMMA_TRIALPARAM_1: maxstep,900
PARAMS_TO_CALIBRATE: newSnowDenMin,newSnowDenMultTemp,Fcapil,k_snow,soil_dens_intr,albedoDecayRate,tempCritRain,k_soil,vGn_n,theta_sat,theta_res,zScale_TOPMODEL,k_macropore
BASIN_PARAMS_TO_CALIBRATE: basin__aquiferHydCond,basin__aquiferBaseflowExp,basin__aquiferScaleFactor
DECISION_OPTIONS:
  snowIncept:
  - lightSnow
  - stickySnow
  windPrfile:
  - logBelowCanopy
  - exponential
  compaction:
  - consettl
  - anderson
SETTINGS_SUMMA_PATH: default
SETTINGS_SUMMA_FILEMANAGER: fileManager.txt
SETTINGS_SUMMA_FORCING_LIST: forcingFileList.txt
SETTINGS_SUMMA_COLDSTATE: coldState.nc
SETTINGS_SUMMA_TRIALPARAMS: trialParams.nc
SETTINGS_SUMMA_ATTRIBUTES: attributes.nc
SETTINGS_SUMMA_OUTPUT: outputControl.txt
SETTINGS_SUMMA_BASIN_PARAMS_FILE: basinParamInfo.txt
SETTINGS_SUMMA_LOCAL_PARAMS_FILE: localParamInfo.txt
SUMMA_INSTALL_PATH: default
SUMMA_EXE: summa_sundials.exe
SETTINGS_SUMMA_USE_PARALLEL_SUMMA: false
SETTINGS_SUMMA_CPUS_PER_TASK: 32
SETTINGS_SUMMA_TIME_LIMIT: 01:00:00
SETTINGS_SUMMA_MEM: 0
SETTINGS_SUMMA_GRU_COUNT: 118
SETTINGS_SUMMA_GRU_PER_JOB: 10
SETTINGS_SUMMA_PARALLEL_PATH: default
SETTINGS_SUMMA_PARALLEL_EXE: summa_actors.exe
SETTINGS_MIZU_WITHIN_BASIN: 0
SETTINGS_MIZU_ROUTING_DT: 3600
SETTINGS_MIZU_ROUTING_UNITS: m/s
SETTINGS_MIZU_ROUTING_VAR: averageRoutedRunoff
SETTINGS_MIZU_OUTPUT_FREQ: single
SETTINGS_MIZU_OUTPUT_VARS: 1
SETTINGS_MIZU_MAKE_OUTLET: n/a
SETTINGS_MIZU_NEEDS_REMAP: false
SETTINGS_MIZU_PATH: default
INSTALL_PATH_MIZUROUTE: default
EXE_NAME_MIZUROUTE: mizuroute.exe
SETTINGS_MIZU_TOPOLOGY: topology.nc
SETTINGS_MIZU_PARAMETERS: param.nml.default
SETTINGS_MIZU_CONTROL_FILE: mizuroute.control
SETTINGS_MIZU_REMAP: routing_remap.nc
EXPERIMENT_OUTPUT_SUMMA: default
EXPERIMENT_OUTPUT_MIZUROUTE: default
EXPERIMENT_LOG_MIZUROUTE: default
EXPERIMENT_LOG_SUMMA: default
FLASH_LOAD: true
FLASH_HIDDEN_SIZE: 128
FLASH_NUM_LAYERS: 3
FLASH_EPOCHS: 300
FLASH_BATCH_SIZE: 64
FLASH_LEARNING_RATE: 0.001
FLASH_LEARNING_PATIENCE: 30
FLASH_LOOKBACK: 700
FLASH_DROPOUT: 0.2
FLASH_L2_REGULARIZATION: 1e-6
FLASH_USE_ATTENTION: true
SUMMAFLOW: spatial
UNIFY_SOIL: false
MINIMUM_LAND_FRACTION: 0.01
NUM_LAND_COVER: 20
LANDCOVER_YEAR: '2020'
GEOFABRIC_MAPPING:
  basinID:
    in_varname: GRU_ID
  nextDownID:
    in_varname: DSLINKO
  area:
    in_varname: HRU_area
    in_units: m^2
    out_units: m^2
  rivlen:
    in_varname: Length
    in_units: m
    out_units: m
SIM_REACH_ID: 229
SIMULATIONS_PATH: default
OBSERVATIONS_PATH: default
STREAMFLOW_DATA_PROVIDER: WSC
STREAMFLOW_RAW_PATH: default
STREAMFLOW_RAW_NAME: Discharge.Working@09AH001.20110101_corrected.csv
STREAMFLOW_PROCESSED_PATH: default
OPTMIZATION_ALOGORITHM: NSGA-II
OPTIMIZATION_METRIC: KGE
MOO_OPTIMIZATION_METRICS: KGE,NSE
NUMBER_OF_OBJECTIVES: 2
POPULATION_SIZE: 100
NUMBER_OF_ITERATIONS: 200
NUMBER_OF_GENERATIONS: 10
SWRMSIZE: 40
NGSIZE: 10
DIAGNOSTIC_FREQUENCY: 10
OSTRICH_ALGORITHM: ParallelDDS
OSTRICH_METRICS: GCOP
DDS_R: 0.2
SCE_BUDGET: 10000
SCE_LOOP_STAGNATION: 5
SCE_PCT_CHANGE: 0.01
SCE_POP_CONV: 0.001
SCE_NUM_COMPLEXES: 3
SCE_POINTS_PER_COMPLEX: 19
SCE_POINTS_PER_SUBCOMPLEX: 10
SCE_NUM_EVOLUTION_STEPS: 19
SCE_MIN_COMPLEXES: 3
SCE_USE_INITIAL_POINT: false
PSO_SWARM_SIZE: 20
PSO_NUM_GENERATIONS: 50
PSO_CONSTRICTION_FACTOR: 1.0
PSO_COGNITIVE_PARAM: 1.5
PSO_SOCIAL_PARAM: 1.5
PSO_INERTIA_WEIGHT: 0.7
PSO_INERTIA_REDUCTION_RATE: 0.99
PSO_INIT_POPULATION_METHOD: Random
PSO_CONVERGENCE_VAL: 0.0001
RUN_SENSITIVITY_ANALYSIS: true
RUN_DECISION_ANALYSIS: true
OSTRICH_PATH: default
OSTRICH_EXE: OstrichMPI
OSTRICH_OUTPUT_FILE: ostrich_output.txt
OPTIMIZATION_RESULTS_FILE: default
ITERATION_RESULTS_FILE: default
RUN_LARGE_SAMPLE_EMULATION: true
EMULATION_NUM_SAMPLES: 100
EMULATION_SEED: 22
EMULATION_SAMPLING_METHOD: lhs
EMULATION_CREATE_INDIVIDUAL_RUNS: true
EMULATION_RUN_ENSEMBLE: true
EMULATION_PARALLEL_ENSEMBLE: false
EMULATION_MAX_PARALLEL_JOBS: 100
EMULATION_ANALYZE_PARAMETERS: true
EMULATION_ANALYZE_ENSEMBLE: true
EMULATION_SKIP_MIZUROUTE: false
EMULATION_RETRY_FAILED_RUNS: true
EMULATION_MAX_RETRIES: 3
EMULATION_USE_ATTRIBUTES: false
RUN_RANDOM_FOREST_EMULATION: true
EMULATION_TARGET_METRIC: KGE
EMULATION_RF_N_ESTIMATORS: 100
EMULATION_RF_MAX_DEPTH: null
EMULATION_N_OPTIMIZATION_RUNS: 10
EMULATION_ITERATIONS: 10
EMULATION_STOP_CRITERIA: 0.01
RUN_ITERATIVE_OPTIMISATION: true
ITERATIVE_OPTIMIZATION_ALGORITHM: PSO
NUMBER_OF_COMPLEXES: 2
POINTS_PER_SUBCOMPLEX: 5
NUMBER_OF_EVOLUTION_STEPS: 20
EVOLUTION_STAGNATION: 5
PERCENT_CHANGE_THRESHOLD: 0.01
PROCESS_CHARACTERISTIC_ATTRIBUTES: true
ATTRIBUTES_PROCESS_LUMPED: true
ATTRIBUTES_OVERWRITE_EXISTING: false
ATTRIBUTES_DATA_DIR: /work/comphyd_lab/data/_to-be-moved/NorthAmerica_geospatial/
ATTRIBUTES_SOILGRIDS_PATH: default
ATTRIBUTES_PELLETIER_PATH: default
ATTRIBUTES_MERIT_PATH: default
ATTRIBUTES_MODIS_PATH: default
ATTRIBUTES_GLCLU_PATH: default
ATTRIBUTES_FOREST_HEIGHT_PATH: default
ATTRIBUTES_WORLDCLIM_PATH: default
ATTRIBUTES_GLIM_PATH: default
ATTRIBUTES_GROUNDWATER_PATH: default
ATTRIBUTES_STREAMFLOW_PATH: default
HRU_GAUGE_MAPPING: {}
ATTRIBUTES_GLWD_PATH: default
ATTRIBUTES_HYDROLAKES_PATH: default
ATTRIBUTES_OUTPUT_DIR: default
