### CONFLUENCE configuration file

# Note on path specification
# If deviating from default paths, a full path must be specified. E.g. '/home/user/non-default/path'

# Model domain settings
CONFLUENCE_DATA_DIR: "/Users/darrieythorsson/compHydro/data/CONFLUENCE_data"
CONFLUENCE_CODER_DIR: "/Users/darrieythorsson/compHydro/code/CONFLUENCE"
DOMAIN_NAME: "Bow_at_Banff"

# Computatational settings
MPI_PROCESSES: 4                                               # Adjust this number based on your system's capabilities
FORCE_RUN_ALL_STEPS: true                                      # Run all steps in the workflow and overwrite existing files

## Geospatial settings
# Geospatial domain representation settings
DOMAIN_DEFINITION_METHOD: delineate_geofabric                  # Define domain representation method. Options subset_geofabric, delineate_geofabric, lumped_watershed
GEOFABRIC_TYPE: TDX                                            # Source geofabric to subset from, options Merit, TDX, NWS
SOURCE_GEOFABRIC_BASINS_PATH: /Users/darrieythorsson/compHydro/data/CWARHM_data/domain_NorthAmerica/shapefiles/catchment/7020021430-basins.gpkg                                   # Path to source geofabric basins
SOURCE_GEOFABRIC_RIVERS_PATH: /Users/darrieythorsson/compHydro/data/CWARHM_data/domain_NorthAmerica/shapefiles/river_network/7020021430-streamnet.gpkg                                   # Path to source geofabric rivers
OUTPUT_BASINS_PATH: default                                    # If 'default', uses 'root_path/domain_[name]/shapefiles/river_basins/[domain_name]_riverBasins.shp'
OUTPUT_RIVERS_PATH: default                                    # If 'default', uses 'root_path/domain_[name]/shapefiles/river_network/[domain_name]_riverNetwork.shp'
DEM_PATH: default                                              # If 'default', uses 'root_path/domain_[name]/attributes/elevation/dem.tiff'
OUTPUT_DIR: default                                            # If 'default', uses 'root_path/domain_[name]/shapefiles/r
STREAM_THRESHOLD: 5000                                         # Threshold flow accumulation for stream vectorisation
TAUDEM_DIR: default                                            # If 'default', uses 'root_path/installs/TauDEM 
CLEANUP_INTERMEDIATE_FILES: True                               # Remove temporary files from delieation

# Domain discretization settings
DOMAIN_DISCRETIZATION: None                               # Method to discretize modelling domain, options: elevation, soil_class, land_class, radiation, combined, none
COMBINED_DISCRETIZATION_METHODS: elevation, radiation          # Combined methods to discretize modelling domains 
ELEVATION_BAND_SIZE: 300                                       # Elevation band size in meters
MIN_HRU_SIZE: 3                                                # Minimum HRU size in km^2
CATCHMENT_PLOT_DIR: default                                    # Directory to output plots of domain catchment
SOIL_CLASS_PATH: default                                       # Path to soil classification raster
LAND_CLASS_PATH: default                                       # Path to land classification raster      
RADIATION_PATH: default                                        # Path to radiation classification raster
RADIATION_CLASS_NUMBER: 4                                      # Number of radiation classes

# Shapefile settings
RIVER_BASINS_PATH: default                                     # Path to delineated river basins shapefile
CATCHMENT_PATH: default                                        # Path to domain catchment shapefile
CATCHMENT_SHP_NAME: default                                    # Name of domain catchment shapefile used in data acquisition and modelling 
RIVER_BASIN_SHP_RM_HRUID: "COMID"                              # HRU ID column in riverBasin shapefile

# Pour point settings
POUR_POINT_SHP_PATH: default                                   # If 'default', uses 'root_path/domain_[name]/shapefiles/pour_point'.
POUR_POINT_SHP_NAME: default                                   # If 'default', uses '[domain_name]_pourPoint.shp'.
POUR_POINT_COORDS: 51.1722/-115.5717                           # Pour point coordinates lat/lon, if default use user provided shapefile. 

# Tool paths
DATATOOL_PATH: default                                         # Path to datatool executable 
GISTOOL_PATH: default                                          # Path to gistool executable
EASYMORE_PATH: easymore cli                                    # Path to easymore executable

# Tool settings
DATATOOL_DATASET_ROOT: "/path/to/datatool/datasets"            # Path to datatool datasets root directory
DATATOOL_CACHE: "/path/to/datatool/cache"                      # Cache directory used in datatool
TOOL_ACCOUNT: def-mclark-ab                                    # HPC account for running datatool

GISTOOL_DATASET_ROOT: "/path/to/gistool/datasets"              # Path to gistool datasets root directory
GISTOOL_LIB_PATH: "/path/to/gistool/lib"                       # Path to gistool libraries
GISTOOL_CACHE: "/path/to/gistool/cache"                        # Path to gistool cache directory

EASYMORE_CACHE: "/path/to/easymore/cache"                      # Path to easymore cache directory
EASYMORE_JOB_CONF: "installs/MAF/02_model_agnostic_component/easymore-job.slurm" #Path to easymore job config

# Data acquisition settings
FORCING_DATASET: "RDRS_v2.1"                                   # Forcing dataset to use
FORCING_START_YEAR: "2010"                                     # Forcing start year
FORCING_END_YEAR: "2020"                                       # Forcing end year 
FORCING_VARIABLES:                                             # Forcing dataset variables to use acquire
  - "RDRS_v2.1_P_P0_SFC"
  - "RDRS_v2.1_P_HU_09944"
  - "RDRS_v2.1_P_TT_09944"
  - "RDRS_v2.1_P_UVC_09944"
  - "RDRS_v2.1_A_PR0_SFC"
  - "RDRS_v2.1_P_FB_SFC"
  - "RDRS_v2.1_P_FI_SFC"

# Data cleanup settings
UNIFY_SOIL: false                                              # Merge small soil areas
MINIMUM_LAND_FRACTION: 0.01                                    # Minimum land cover classification fraction to include
NUM_LAND_COVER: 20                                             # Number of land cover classes

# Other settings
LANDCOVER_YEAR: "2020"                                         # Year of land cover classification

## Model settings
HYDROLOGICAL_MODEL: SUMMA                                      # Hydrological model used, options: SUMMA, MESH (tbi), HYPE (tbi)
ROUTING_MODEL: mizuroute                                       # Routing model used, options: mizuroute, HEC-RAS (tbi)

# SUMMA settings
# Mizuroute settings
# MESH settings
# HYPE settings

## Optimization settings
#Ostrich settings