ANALYSES:
- benchmarking
APPLY_LAPSE_RATE: true
ATTRIBUTES_DATA_DIR: /work/comphyd_lab/data/_to-be-moved/NorthAmerica_geospatial/
ATTRIBUTES_FOREST_HEIGHT_PATH: default
ATTRIBUTES_GLCLU_PATH: default
ATTRIBUTES_GLIM_PATH: default
ATTRIBUTES_GLWD_PATH: default
ATTRIBUTES_GROUNDWATER_PATH: default
ATTRIBUTES_HYDROLAKES_PATH: default
ATTRIBUTES_MERIT_PATH: default
ATTRIBUTES_MODIS_PATH: default
ATTRIBUTES_OUTPUT_DIR: default
ATTRIBUTES_PELLETIER_PATH: default
ATTRIBUTES_SOILGRIDS_PATH: default
ATTRIBUTES_STREAMFLOW_PATH: default
ATTRIBUTES_WORLDCLIM_PATH: default
BASIN_PARAMS_TO_CALIBRATE: routingGammaScale
BOUNDING_BOX_COORDS: 51.76/-116.55/50.95/-115.5
CALIBRATE_DEPTH: false
CALIBRATION_PERIOD: 1982-01-01, 1990-12-30
CATCHMENT_PATH: default
CATCHMENT_PLOT_DIR: default
CATCHMENT_SHP_AREA: HRU_area
CATCHMENT_SHP_GRUID: GRU_ID
CATCHMENT_SHP_HRUID: HRU_ID
CATCHMENT_SHP_LAT: center_lat
CATCHMENT_SHP_LON: center_lon
CATCHMENT_SHP_NAME: default
CLEANUP_INTERMEDIATE_FILES: true
CLUSTER_JSON: /work/comphyd_lab/users/darri/data/CONFLUENCE_data/installs/datatool/etc/clusters/ucalgary-arc.json
CONFLUENCE_CODE_DIR: /Users/darrieythorsson/compHydro/code/CONFLUENCE
CONFLUENCE_DATA_DIR: /Users/darrieythorsson/compHydro/data/CONFLUENCE_data
DATATOOL_CACHE: /home/darri.eythorsson
DATATOOL_DATASET_ROOT: /work/comphyd_lab/data/meteorological-data/
DATATOOL_PATH: default
DDS_R: 0.4
DELINEATE_BY_POURPOINT: true
DEM_NAME: default
DEM_PATH: default
DEPTH_SHAPE_FACTOR_BOUNDS:
- 0.1
- 3.0
DEPTH_TOTAL_MULT_BOUNDS:
- 0.1
- 5.0
DE_CROSSOVER_RATE: 0.9
DE_SCALING_FACTOR: 0.5
DOMAIN_DEFINITION_METHOD: point
DOMAIN_DISCRETIZATION: GRUs
DOMAIN_NAME: paradise
DOWNLOAD_FLUXNET: 'false'
DOWNLOAD_SNOTEL: 'false'
DOWNLOAD_USGS_DATA: false
DOWNLOAD_USGS_GW: 'true'
DOWNLOAD_WSC_DATA: true
EASYMORE_CACHE: /home/darri.eythorsson/easymore/
EASYMORE_CLIENT: easymore cli
EASYMORE_JOB_CONF: installs/MAF/02_model_agnostic_component/easymore-job.slurm
ELEVATION_BAND_SIZE: 200
EMULATION_MAX_ITERATIONS': 3
EMULATION_MAX_PARALLEL_JOBS: 100
EMULATION_NUM_SAMPLES: 100
EMULATION_PARALLEL_ENSEMBLE: false
EMULATION_SAMPLING_METHOD: lhs
EMULATION_SEED: 22
EMULATION_SKIP_MIZUROUTE: false
EMULATION_TARGET_METRIC: KGE
EMULATION_USE_ATTRIBUTES: false
EMULATOR_IMPROVEMENT_THRESHOLD: 0.01
EM_EARTH_MAX_EXPANSION: 0.2
EM_EARTH_MIN_BBOX_SIZE: 0.1
EM_EARTH_PRCP_DIR: /anvil/datasets/meteorological/EM-Earth/EM_Earth_v1/deterministic_hourly/prcp/NorthAmerica
EM_EARTH_TMEAN_DIR: /anvil/datasets/meteorological/EM-Earth/EM_Earth_v1/deterministic_hourly/tmean/NorthAmerica
EM_PRCP: prcp_corrected
ENABLE_GAP_FILLING: true
EVALUATION_DATA:
- streamflow
EVALUATION_PERIOD: 2012-01-01, 2023-12-30
EVOLUTION_STAGNATION: 5
EXE_NAME_MIZUROUTE: mizuroute.exe
EXPERIMENT_ID: point_scale_tutorial
EXPERIMENT_LOG_MIZUROUTE: default
EXPERIMENT_LOG_SUMMA: default
EXPERIMENT_OUTPUT_FUSE: default
EXPERIMENT_OUTPUT_MIZUROUTE: default
EXPERIMENT_OUTPUT_SUMMA: default
EXPERIMENT_TIME_END: 2023-12-30 23:00
EXPERIMENT_TIME_START: 1980-01-02 01:00
FLASH_BATCH_SIZE: 64
FLASH_DROPOUT: 0.2
FLASH_EPOCHS: 300
FLASH_HIDDEN_SIZE: 128
FLASH_L2_REGULARIZATION: 1e-6
FLASH_LEARNING_PATIENCE: 30
FLASH_LEARNING_RATE: 0.001
FLASH_LOAD: false
FLASH_LOOKBACK: 700
FLASH_NUM_LAYERS: 3
FLASH_USE_ATTENTION: true
FLASH_USE_SNOW: false
FLUXNET_PATH: /work/comphyd_lab/data/geospatial-data/fluxnet
FLUXNET_STATION: CA-NS7
FORCE_RUN_ALL_STEPS: false
FORCING_DATASET: ERA5
FORCING_MEASUREMENT_HEIGHT: 1.5
FORCING_PATH: default
FORCING_SHAPE_LAT_NAME: lat
FORCING_SHAPE_LON_NAME: lon
FORCING_TIME_STEP_SIZE: 3600
FORCING_VARIABLES: default
FUSE_DECISION_OPTIONS:
  ARCH1:
  - tension1_1
  ARCH2:
  - tens2pll_2
  ESOIL:
  - sequential
  QINTF:
  - intflwnone
  QPERC:
  - perc_f2sat
  QSURF:
  - arno_x_vic
  - prms_varnt
  Q_TDH:
  - rout_gamma
  RFERR:
  - additive_e
  - multiplc_e
  SNOWM:
  - temp_index
  - no_snowmod
FUSE_EXE: fuse.exe
FUSE_INSTALL_PATH: default
GAP_BOUNDARY_MARGIN: 0.1
GAP_DENSITY_THRESHOLD: 0.1
GAP_FILLING_METHODS:
- density
- boundary
- uncertainty
- diversity
GAP_FILLING_SAMPLES: 50
GAP_UNCERTAINTY_PERCENTILE: 90
GEOFABRIC_TYPE: TDX
GISTOOL_DATASET_ROOT: /work/comphyd_lab/data/geospatial-data/
GISTOOL_LIB_PATH: /work/comphyd_lab/envs/r-env/
GISTOOL_PATH: default
GR_EXE: GR.r
GR_INSTALL_PATH: default
HRU_GAUGE_MAPPING: {}
HYDAT_PATH: default
HYDROLOGICAL_MODEL: SUMMA
HYPE_EXE: hype
HYPE_INSTALL_PATH: default
INSTALL_PATH_MIZUROUTE: default
INTERSECT_DEM_NAME: default
INTERSECT_DEM_PATH: default
INTERSECT_LAND_NAME: default
INTERSECT_LAND_PATH: default
INTERSECT_ROUTING_NAME: default
INTERSECT_ROUTING_PATH: default
INTERSECT_SOIL_NAME: default
INTERSECT_SOIL_PATH: default
ITERATIVE_OPTIMIZATION_ALGORITHM: DE
LAND_CLASS_NAME: default
LAND_CLASS_PATH: default
LAPSE_RATE: 0.0065
MESH_EXE: mesh.exe
MIN_GRU_SIZE: 0
MIN_HRU_SIZE: 4
MOVE_OUTLETS_MAX_DISTANCE: 200
MPI_PROCESSES: 1
NN_HIDDEN_LAYERS:
- 100
- 50
NN_LEARNING_RATE: 0.001
NN_MAX_ITERATIONS: 1000
NN_VALIDATION_SPLIT: 0.2
NUMBER_OF_COMPLEXES: 2
NUMBER_OF_EVOLUTION_STEPS: 20
NUMBER_OF_ITERATIONS: 100
OBSERVATIONS_PATH: default
OPTIMISATION_METHODS:
- iteration
- emulation
OPTIMIZATION_METRIC: KGE
OUTPUT_BASINS_PATH: default
OUTPUT_DIR: default
OUTPUT_RIVERS_PATH: default
PARAMS_TO_CALIBRATE: tempCritRain,k_soil,vGn_n,theta_sat,theta_res,rootingDepth,zScale_TOPMODEL,k_macropore
PERCENT_CHANGE_THRESHOLD: 0.01
POINTS_PER_SUBCOMPLEX: 5
POPULATION_SIZE: 30
POUR_POINT_COORDS: 51.1722/-115.5717
POUR_POINT_SHP_NAME: default
POUR_POINT_SHP_PATH: default
PSO_COGNITIVE_PARAM: 1.5
PSO_INERTIA_REDUCTION_RATE: 0.99
PSO_INERTIA_WEIGHT: 0.7
PSO_SOCIAL_PARAM: 1.5
RADIATION_CLASS_NUMBER: 5
RADIATION_PATH: default
RIVER_BASINS_NAME: default
RIVER_BASINS_PATH: default
RIVER_BASIN_SHP_AREA: GRU_area
RIVER_BASIN_SHP_HRU_TO_SEG: gru_to_seg
RIVER_BASIN_SHP_RM_GRUID: GRU_ID
RIVER_NETWORK_SHP_DOWNSEGID: DSLINKNO
RIVER_NETWORK_SHP_LENGTH: Length
RIVER_NETWORK_SHP_NAME: default
RIVER_NETWORK_SHP_PATH: default
RIVER_NETWORK_SHP_SEGID: LINKNO
RIVER_NETWORK_SHP_SLOPE: Slope
ROUTING_MODEL: mizuRoute
RUN_GAP_FILLING_SIMULATIONS: true
RUN_NEURAL_NETWORK_EMULATION: true
RUN_RANDOM_FOREST_EMULATION: false
SETTINGS_FUSE_FILEMANAGER: default
SETTINGS_FUSE_PATH: default
SETTINGS_GR_CONTROL: default
SETTINGS_GR_PATH: default
SETTINGS_HYPE_PATH: default
SETTINGS_MIZU_CONTROL_FILE: mizuroute.control
SETTINGS_MIZU_MAKE_OUTLET: n/a
SETTINGS_MIZU_NEEDS_REMAP: false
SETTINGS_MIZU_OUTPUT_FREQ: single
SETTINGS_MIZU_OUTPUT_VARS: 1
SETTINGS_MIZU_PARAMETERS: param.nml.default
SETTINGS_MIZU_PATH: default
SETTINGS_MIZU_REMAP: routing_remap.nc
SETTINGS_MIZU_ROUTING_DT: 3600
SETTINGS_MIZU_ROUTING_UNITS: m/s
SETTINGS_MIZU_ROUTING_VAR: averageRoutedRunoff
SETTINGS_MIZU_TOPOLOGY: topology.nc
SETTINGS_MIZU_WITHIN_BASIN: 0
SETTINGS_SUMMA_ATTRIBUTES: attributes.nc
SETTINGS_SUMMA_BASIN_PARAMS_FILE: basinParamInfo.txt
SETTINGS_SUMMA_COLDSTATE: coldState.nc
SETTINGS_SUMMA_CONNECT_HRUS: true
SETTINGS_SUMMA_FILEMANAGER: fileManager.txt
SETTINGS_SUMMA_FORCING_LIST: forcingFileList.txt
SETTINGS_SUMMA_LOCAL_PARAMS_FILE: localParamInfo.txt
SETTINGS_SUMMA_OUTPUT: outputControl.txt
SETTINGS_SUMMA_PARALLEL_EXE: summa_actors.exe
SETTINGS_SUMMA_PARALLEL_PATH: default
SETTINGS_SUMMA_PATH: default
SETTINGS_SUMMA_TRIALPARAMS: trialParams.nc
SETTINGS_SUMMA_TRIALPARAM_1: null
SETTINGS_SUMMA_TRIALPARAM_N: 0
SETTINGS_SUMMA_USE_PARALLEL_SUMMA: false
SIMULATIONS_PATH: default
SIM_REACH_ID: 123
SNOTEL_PATH: /work/comphyd_lab/data/geospatial-data/SNOTEL
SNOTEL_STATION: '602'
SOIL_CLASS_NAME: default
SOIL_CLASS_PATH: default
SOURCE_GEOFABRIC_BASINS_PATH: default
SOURCE_GEOFABRIC_RIVERS_PATH: default
SPINUP_PERIOD: 1980-01-02, 1981-12-31
STATION_ID: 05BB001
STREAMFLOW_DATA_PROVIDER: WSC
STREAMFLOW_PROCESSED_PATH: default
STREAMFLOW_RAW_NAME: default
STREAMFLOW_RAW_PATH: default
STREAM_THRESHOLD: 2500
SUMMA_DECISION_OPTIONS:
  LAI_method:
  - monTable
  alb_method:
  - conDecay
  astability:
  - louisinv
  bcLowrSoiH:
  - drainage
  bcLowrTdyn:
  - zeroFlux
  bcUpprSoiH:
  - liq_flux
  bcUpprTdyn:
  - nrg_flux
  canopyEmis:
  - difTrans
  canopySrad:
  - BeersLaw
  compaction:
  - anderson
  fDerivMeth:
  - analytic
  f_Richards:
  - mixdform
  groundwatr:
  - bigBuckt
  hc_profile:
  - constant
  num_method:
  - itertive
  snowIncept:
  - lightSnow
  snowLayers:
  - CLM_2010
  soilCatTbl:
  - ROSETTA
  soilStress:
  - NoahType
  spatial_gw:
  - localColumn
  stomResist:
  - BallBerry
  subRouting:
  - timeDlay
  thCondSnow:
  - jrdn1991
  - smnv2000
  thCondSoil:
  - funcSoilWet
  veg_traits:
  - Raupach_BLM1994
  vegeParTbl:
  - MODIFIED_IGBP_MODIS_NOAH
  windPrfile:
  - logBelowCanopy
SUMMA_EXE: summa_sundials.exe
SUMMA_INSTALL_PATH: default
SUPPLEMENT_FORCING: false
SWRMSIZE: 20
TAUDEM_DIR: default
TOOL_CACHE: /home/darri.eythorsson/cache
USGS_STATION: '06306300'
