APPLY_LAPSE_RATE: true
ATTRIBUTES_DATA_DIR: /work/comphyd_lab/data/_to-be-moved/NorthAmerica_geospatial/
ATTRIBUTES_FOREST_HEIGHT_PATH: default
ATTRIBUTES_GLCLU_PATH: default
ATTRIBUTES_GLIM_PATH: default
ATTRIBUTES_GLWD_PATH: default
ATTRIBUTES_GROUNDWATER_PATH: default
ATTRIBUTES_HYDROLAKES_PATH: default
ATTRIBUTES_MERIT_PATH: default
ATTRIBUTES_MODIS_PATH: default
ATTRIBUTES_OUTPUT_DIR: default
ATTRIBUTES_OVERWRITE_EXISTING: false
ATTRIBUTES_PELLETIER_PATH: default
ATTRIBUTES_PROCESS_LUMPED: true
ATTRIBUTES_SOILGRIDS_PATH: default
ATTRIBUTES_STREAMFLOW_PATH: default
ATTRIBUTES_WORLDCLIM_PATH: default
BASIN_PARAMS_TO_CALIBRATE: basin__aquiferHydCond,basin__aquiferBaseflowExp,basin__aquiferScaleFactor,routingGammaShape,routingGammaScale
BOUNDING_BOX_COORDS: 51.76/-116.55/50.95/-115.5
CALIBRATION_PERIOD: 2013-01-01, 2016-12-31
CATCHMENT_PATH: default
CATCHMENT_PLOT_DIR: default
CATCHMENT_SHP_AREA: HRU_area
CATCHMENT_SHP_GRUID: GRU_ID
CATCHMENT_SHP_HRUID: HRU_ID
CATCHMENT_SHP_LAT: center_lat
CATCHMENT_SHP_LON: center_lon
CATCHMENT_SHP_NAME: default
CLEANUP_INTERMEDIATE_FILES: false
CLUSTER_JSON: /work/comphyd_lab/users/darri/data/CONFLUENCE_data/installs/datatool/etc/clusters/ucalgary-arc.json
COMBINED_DISCRETIZATION_METHODS: elevation, radiation
CONFLUENCE_CODE_DIR: /home/darri.eythorsson/code/CONFLUENCE
CONFLUENCE_DATA_DIR: /work/comphyd_lab/data/CONFLUENCE_data
DATATOOL_CACHE: /home/darri.eythorsson
DATATOOL_DATASET_ROOT: /work/comphyd_lab/data/meteorological-data/
DATATOOL_PATH: default
DATA_ACQUIRE: HPC
DDS_R: 0.2
DECISION_OPTIONS:
  alb_method:
  - conDecay
  - varDecay
  compaction:
  - consettl
  - anderson
  snowIncept:
  - lightSnow
  - stickySnow
  snowLayers:
  - CLM_2010
  - jrdn1991
  thCondSnow:
  - tyen1965
  - melr1977
  - jrdn1991
  - smnv2000
DELINEATE_BY_POURPOINT: true
DEM_NAME: default
DEM_PATH: default
DOMAIN_DEFINITION_METHOD: delineate
DOMAIN_DISCRETIZATION: elevation
DOMAIN_NAME: Bow_at_Banff_elevation
DOWNLOAD_USGS_DATA: true
DOWNLOAD_WSC_DATA: true
EASYMORE_CACHE: /home/darri.eythorsson/easymore/
EASYMORE_CLIENT: easymore cli
EASYMORE_JOB_CONF: installs/MAF/02_model_agnostic_component/easymore-job.slurm
ELEVATION_BAND_SIZE: 200
EMULATION_ANALYZE_ENSEMBLE: true
EMULATION_ANALYZE_PARAMETERS: true
EMULATION_CREATE_INDIVIDUAL_RUNS: true
EMULATION_ITERATIONS: 10
EMULATION_MAX_PARALLEL_JOBS: 100
EMULATION_MAX_RETRIES: 3
EMULATION_NUM_SAMPLES: 100
EMULATION_N_OPTIMIZATION_RUNS: 10
EMULATION_PARALLEL_ENSEMBLE: false
EMULATION_RETRY_FAILED_RUNS: true
EMULATION_RF_MAX_DEPTH: null
EMULATION_RF_N_ESTIMATORS: 100
EMULATION_RUN_ENSEMBLE: true
EMULATION_SAMPLING_METHOD: lhs
EMULATION_SEED: 22
EMULATION_SKIP_MIZUROUTE: false
EMULATION_STOP_CRITERIA: 0.01
EMULATION_TARGET_METRIC: KGE
EMULATION_USE_ATTRIBUTES: false
EVALUATION_PERIOD: 2017-01-01, 2022-12-31
EVOLUTION_STAGNATION: 5
EXE_NAME_MIZUROUTE: mizuroute.exe
EXPERIMENT_ID: elevation_tutorial
EXPERIMENT_LOG_MIZUROUTE: default
EXPERIMENT_LOG_SUMMA: default
EXPERIMENT_OUTPUT_FUSE: default
EXPERIMENT_OUTPUT_MIZUROUTE: default
EXPERIMENT_OUTPUT_SUMMA: default
EXPERIMENT_TIME_END: 2018-12-31 23:00
EXPERIMENT_TIME_START: 2018-01-01 01:00
FLASH_BATCH_SIZE: 64
FLASH_DROPOUT: 0.2
FLASH_EPOCHS: 300
FLASH_HIDDEN_SIZE: 128
FLASH_L2_REGULARIZATION: 1e-6
FLASH_LEARNING_PATIENCE: 30
FLASH_LEARNING_RATE: 0.001
FLASH_LOAD: false
FLASH_LOOKBACK: 700
FLASH_NUM_LAYERS: 3
FLASH_USE_ATTENTION: true
FLASH_USE_SNOW: false
FORCE_RUN_ALL_STEPS: false
FORCING_DATASET: ERA5
FORCING_MEASUREMENT_HEIGHT: 2
FORCING_PATH: default
FORCING_SHAPE_LAT_NAME: lat
FORCING_SHAPE_LON_NAME: lon
FORCING_TIME_STEP_SIZE: 3600
FORCING_VARIABLES: default
FUSE_EXE: fuse.exe
FUSE_INSTALL_PATH: default
FUSE_spatial: lumped
GEOFABRIC_TYPE: TDX
GISTOOL_DATASET_ROOT: /work/comphyd_lab/data/geospatial-data/
GISTOOL_LIB_PATH: /work/comphyd_lab/envs/r-env/
GISTOOL_PATH: default
GR_EXE: GR.r
GR_INSTALL_PATH: default
GR_spatial: lumped
HRU_GAUGE_MAPPING: {}
HYDAT_PATH: default
HYDROLOGICAL_MODEL: SUMMA
HYPE_EXE: hype
HYPE_INSTALL_PATH: default
INSTALL_PATH_MIZUROUTE: default
INTERSECT_DEM_NAME: default
INTERSECT_DEM_PATH: default
INTERSECT_LAND_NAME: default
INTERSECT_LAND_PATH: default
INTERSECT_ROUTING_NAME: default
INTERSECT_ROUTING_PATH: default
INTERSECT_SOIL_NAME: default
INTERSECT_SOIL_PATH: default
ITERATIVE_OPTIMIZATION_ALGORITHM: PSO
LAND_CLASS_NAME: default
LAND_CLASS_PATH: default
LAPSE_RATE: 0.0065
LUMPED_WATERSHED_METHOD: TauDEM
MIN_GRU_SIZE: 0
MIN_HRU_SIZE: 4
MOVE_OUTLETS_MAX_DISTANCE: 200
MPI_PROCESSES: 1
NUMBER_OF_COMPLEXES: 2
NUMBER_OF_EVOLUTION_STEPS: 20
NUMBER_OF_ITERATIONS: 200
OBSERVATIONS_PATH: default
OPTIMIZATION_METRIC: KGE
OUTPUT_BASINS_PATH: default
OUTPUT_DIR: default
OUTPUT_RIVERS_PATH: default
PARAMS_TO_CALIBRATE: newSnowDenMin,newSnowDenMultTemp,Fcapil,k_snow,soil_dens_intr,albedoDecayRate,tempCritRain,k_soil,vGn_n,theta_sat,theta_res,zScale_TOPMODEL,k_macropore,Frad_vis,rootingDepth,leafExchangeCoeff,critSoilWilting
PERCENT_CHANGE_THRESHOLD: 0.01
POINTS_PER_SUBCOMPLEX: 5
POPULATION_SIZE: 100
POUR_POINT_COORDS: 51.1722/-115.5717
POUR_POINT_SHP_NAME: default
POUR_POINT_SHP_PATH: default
PROCESS_CHARACTERISTIC_ATTRIBUTES: false
PSO_COGNITIVE_PARAM: 1.5
PSO_INERTIA_REDUCTION_RATE: 0.99
PSO_INERTIA_WEIGHT: 0.7
PSO_SOCIAL_PARAM: 1.5
RADIATION_CLASS_NUMBER: 5
RADIATION_PATH: default
RIVER_BASINS_NAME: default
RIVER_BASINS_PATH: default
RIVER_BASIN_SHP_AREA: GRU_area
RIVER_BASIN_SHP_HRU_TO_SEG: gru_to_seg
RIVER_BASIN_SHP_RM_GRUID: GRU_ID
RIVER_NETWORK_SHP_DOWNSEGID: DSLINKNO
RIVER_NETWORK_SHP_LENGTH: Length
RIVER_NETWORK_SHP_NAME: default
RIVER_NETWORK_SHP_PATH: default
RIVER_NETWORK_SHP_SEGID: LINKNO
RIVER_NETWORK_SHP_SLOPE: Slope
ROUTING_MODEL: mizuRoute
RUN_DECISION_ANALYSIS: true
RUN_ITERATIVE_OPTIMISATION: true
RUN_LARGE_SAMPLE_EMULATION: true
RUN_RANDOM_FOREST_EMULATION: true
RUN_SENSITIVITY_ANALYSIS: true
SETTINGS_FUSE_FILEMANAGER: default
SETTINGS_FUSE_PATH: default
SETTINGS_GR_CONTROL: default
SETTINGS_GR_PATH: default
SETTINGS_HYPE_PATH: default
SETTINGS_MIZU_CONTROL_FILE: mizuroute.control
SETTINGS_MIZU_MAKE_OUTLET: n/a
SETTINGS_MIZU_NEEDS_REMAP: false
SETTINGS_MIZU_OUTPUT_FREQ: single
SETTINGS_MIZU_OUTPUT_VARS: 1
SETTINGS_MIZU_PARAMETERS: param.nml.default
SETTINGS_MIZU_PATH: default
SETTINGS_MIZU_REMAP: routing_remap.nc
SETTINGS_MIZU_ROUTING_DT: 3600
SETTINGS_MIZU_ROUTING_UNITS: m/s
SETTINGS_MIZU_ROUTING_VAR: averageRoutedRunoff
SETTINGS_MIZU_TOPOLOGY: topology.nc
SETTINGS_MIZU_WITHIN_BASIN: 0
SETTINGS_SUMMA_ATTRIBUTES: attributes.nc
SETTINGS_SUMMA_BASIN_PARAMS_FILE: basinParamInfo.txt
SETTINGS_SUMMA_COLDSTATE: coldState.nc
SETTINGS_SUMMA_CONNECT_HRUS: true
SETTINGS_SUMMA_FILEMANAGER: fileManager.txt
SETTINGS_SUMMA_FORCING_LIST: forcingFileList.txt
SETTINGS_SUMMA_LOCAL_PARAMS_FILE: localParamInfo.txt
SETTINGS_SUMMA_OUTPUT: outputControl.txt
SETTINGS_SUMMA_PARALLEL_EXE: summa.exe
SETTINGS_SUMMA_PARALLEL_PATH: default
SETTINGS_SUMMA_PATH: default
SETTINGS_SUMMA_TRIALPARAMS: trialParams.nc
SETTINGS_SUMMA_USE_PARALLEL_SUMMA: false
SIMULATIONS_PATH: default
SIM_REACH_ID: 228
SOIL_CLASS_NAME: default
SOIL_CLASS_PATH: default
SOURCE_GEOFABRIC_BASINS_PATH: default
SOURCE_GEOFABRIC_RIVERS_PATH: default
SPATIAL_MODE: Distributed
SPINUP_PERIOD: 2011-01-01, 2012-12-31
STATION_ID: 05BB001
STREAMFLOW_DATA_PROVIDER: WSC
STREAMFLOW_PROCESSED_PATH: default
STREAMFLOW_RAW_NAME: default
STREAMFLOW_RAW_PATH: default
STREAM_THRESHOLD: 5000
SUMMA_EXE: summa.exe
SUMMA_INSTALL_PATH: default
SWRMSIZE: 40
TAUDEM_DIR: default
TOOL_CACHE: /home/darri.eythorsson/cache
