### CONFLUENCE configuration file

# Note on path specification
# If deviating from default paths, a full path must be specified. E.g. '/home/user/non-default/path'

# Model domain settings
CONFLUENCE_DATA_DIR: "/Users/darrieythorsson/compHydro/data/CONFLUENCE_data"
CONFLUENCE_CODE_DIR: "/Users/darrieythorsson/compHydro/code/CONFLUENCE"
DOMAIN_NAME: "Baker_Creek"

# Experiment settings
EXPERIMENT_ID: run_1                                           # Name of experiment
EXPERIMENT_TIME_START: default                                 # Start time of experiment e.g. '2010-01-01 00:00'
EXPERIMENT_TIME_END: default                                   # End time of experiment e.g. '2010-12-31 23:00'
EXPERIMENT_OUTPUT_SUMMA: default                               # If 'default', uses 'root_path/domain_[name]/simulations/[experiment_id]/SUMMA'.
EXPERIMENT_OUTPUT_MIZUROUTE: default                           # If 'default', uses 'root_path/domain_[name]/simulations/[experiment_id]/mizuRoute'.
EXPERIMENT_LOG_MIZUROUTE: default                              # Path to mizuroute experiment log file
EXPERIMENT_OUTPUT_MIZUROUTE: default                           # Path to mizuroute output
EXPERIMENT_BACKUP_SETTINGS: yes                                # Backup experiment settings in output folder, options yes or no.
EXPERIMENT_LOG_SUMMA: default                                  # Path to SUMMA experiment log file
EXPERIMENT_OUTPUT_SUMMA: default                               # Path to SUMMA output

# Computatational settings
MPI_PROCESSES: 4                                               # Adjust this number based on your system's capabilities
FORCE_RUN_ALL_STEPS: false                                     # Run all steps in the workflow and overwrite existing files

## Geospatial settings
# Geospatial domain representation settings
DOMAIN_DEFINITION_METHOD: delineate_geofabric                  # Define domain representation method. Options subset_geofabric, delineate_geofabric, lumped_watershed
GEOFABRIC_TYPE: TDX                                            # Source geofabric to subset from, options Merit, TDX, NWS
SOURCE_GEOFABRIC_BASINS_PATH: /Users/darrieythorsson/compHydro/data/CWARHM_data/domain_NorthAmerica/shapefiles/catchment/7020021430-basins.gpkg                                   # Path to source geofabric basins
SOURCE_GEOFABRIC_RIVERS_PATH: /Users/darrieythorsson/compHydro/data/CWARHM_data/domain_NorthAmerica/shapefiles/river_network/7020021430-streamnet.gpkg                                   # Path to source geofabric rivers
OUTPUT_BASINS_PATH: default                                    # If 'default', uses 'root_path/domain_[name]/shapefiles/river_basins/[domain_name]_riverBasins.shp'
OUTPUT_RIVERS_PATH: default                                    # If 'default', uses 'root_path/domain_[name]/shapefiles/river_network/[domain_name]_riverNetwork.shp'
DEM_PATH: default                                              # If 'default', uses 'root_path/domain_[name]/attributes/elevation/dem.tiff'
OUTPUT_DIR: default                                            # If 'default', uses 'root_path/domain_[name]/shapefiles/r
STREAM_THRESHOLD: 100                                         # Threshold flow accumulation for stream vectorisation
TAUDEM_DIR: default                                            # If 'default', uses 'root_path/installs/TauDEM 
CLEANUP_INTERMEDIATE_FILES: True                               # Remove temporary files from delieation

# Domain discretization settings
DOMAIN_DISCRETIZATION: land_class                               # Method to discretize modelling domain, options: elevation, soil_class, land_class, radiation, combined, none
COMBINED_DISCRETIZATION_METHODS: elevation, radiation          # Combined methods to discretize modelling domains 
ELEVATION_BAND_SIZE: 10                                       # Elevation band size in meters
MIN_HRU_SIZE: 0.1                                                # Minimum HRU size in km^2
CATCHMENT_PLOT_DIR: default                                    # Directory to output plots of domain catchment
SOIL_CLASS_PATH: default                                       # Path to soil classification raster
LAND_CLASS_PATH: default                                       # Path to land classification raster      
RADIATION_PATH: default                                        # Path to radiation classification raster
RADIATION_CLASS_NUMBER: 5                                      # Number of radiation classes

# Shapefile settings
CATCHMENT_PATH: default                                        # Path to domain catchment shapefile
CATCHMENT_SHP_NAME: Baker_Creek_HRUs_landclass.shp            # Name of domain catchment shapefile used in data acquisition and modelling 
CATCHMENT_SHP_LAT: cent_lat                                    # Name of the latitude column. Should be a value representative for the HRU. Typically the centroid.
CATCHMENT_SHP_LON: cent_lon                                    # Name of the longitude column. Should be a value representative for the HRU. Typically the centroid.
CATCHMENT_SHP_AREA: area                                       # Name of the catchment area column. Area must be in units [m^2]
CATCHMENT_SHP_HRUID: hruNo                                     # HRU ID column in riverBasin shapefile
CATCHMENT_SHP_GRUID: COMID                                     # GRU ID column in riverBasin shapefile

RIVER_BASIN_SHP_RM_HRUID: hruNo                                # HRU ID column in riverBasin shapefile
RIVER_BASIN_SHP_RM_GRUID: COMID                                # GRU ID column in riverBasin shapefile
RIVER_BASIN_SHP_HRU_TO_SEG: COMID                              # Name of the column that shows which river segment each HRU connects to.
RIVER_BASIN_SHP_AREA: area                                     # Name of the catchment area column. Area must be in units [m^2]

RIVER_NETWORK_SHP_PATH: default                                # Path to river network shapefile
RIVER_NETWORK_SHP_NAME: Bow_at_Banff_riverNetwork_delineated.shp # Name of domain river network shapefile 
RIVER_NETWORK_SHP_LENGTH: Length                               # Name of the segment length column. Length must be in units [m].
RIVER_NETWORK_SHP_SEGID: COMID                                 # Name of the segment ID column.
RIVER_NETWORK_SHP_DOWNSEGID: DSLINKNO                          # Name of the downstream segment ID column.
RIVER_NETWORK_SHP_SLOPE: Slope                                 # Name of the slope column. Slope must be in in units [length/length].
RIVER_BASINS_PATH: default                                     # Path to delineated river basins shapefile
RIVER_BASINS_NAME: Baker_Creek_167_subbasins_local.shp         # Name of river basin shapefile

# Pour point settings
POUR_POINT_SHP_PATH: default                                   # If 'default', uses 'root_path/domain_[name]/shapefiles/pour_point'.
POUR_POINT_SHP_NAME: default                                   # If 'default', uses '[domain_name]_pourPoint.shp'.
POUR_POINT_COORDS: 62.5133/-114.4097                           # Pour point coordinates lat/lon, if default use user provided shapefile. 

# Bounding Box Coords
BOUNDING_BOX_COORDS: 62.72/-114.58/62.49/-114.31               # Coordinates of shapefile bounding box. 

# Intersection settings
INTERSECT_SOIL_PATH: default                                   # If 'default', uses 'root_path/domain_[name]/shapefiles/catchment_intersection/with_soilgrids'.
INTERSECT_SOIL_NAME: catchment_with_soilgrids.shp              # Name of the shapefile with intersection between catchment and SOILGRIDS-derived USDA soil classes, stored in columns 'USDA_{1,...n}'
INTERSECT_ROUTING_PATH: default                                # If 'default', uses 'root_path/domain_[name]/shapefiles/catchment_intersection/with_routing'.
INTERSECT_ROUTING_NAME: catchment_with_routing_basins.shp      # Name of the shapefile with intersection between hydrologic model catchments and routing model catchments.

# Tool paths
DATATOOL_PATH: default                                         # Path to datatool executable 
GISTOOL_PATH: default                                          # Path to gistool executable
EASYMORE_CLIENT: easymore cli                                  # Name of easymore client

# Tool settings
DATATOOL_DATASET_ROOT: /project/rrg-mclark/data/meteorological-data/            # Path to datatool datasets root directory
DATATOOL_CACHE: /home/darri/cache/                             # Cache directory used in datatool
TOOL_ACCOUNT: def-mclark-ab                                    # HPC account for running datatool
GISTOOL_DATASET_ROOT: /project/rrg-mclark/data/geospatial-data/             # Path to gistool datasets root directory
GISTOOL_LIB_PATH: /project/rrg-mclark/lib/                      # Path to gistool libraries
GISTOOL_CACHE: /home/darri/cache/                               # Path to gistool cache directory
EASYMORE_CACHE: /home/darri/easymore/                              # Path to easymore cache directory
EASYMORE_JOB_CONF: "installs/MAF/02_model_agnostic_component/easymore-job.slurm" #Path to easymore job config



# Data acquisition settings
FORCING_DATASET: "RDRS"                                        # Forcing dataset to use
FORCING_START_YEAR: "2010"                                     # Forcing start year
FORCING_END_YEAR: "2020"                                       # Forcing end year 
FORCING_VARIABLES:                                             # Forcing dataset variables to use acquire
  - "RDRS_v2.1_P_P0_SFC"                                       # ERA5 variables | longitude,latitude,time,LWRadAtm,SWRadAtm,pptrate,airpres,airtemp,spechum,windspd
  - "RDRS_v2.1_P_HU_09944"                                     # CARRA variables | 10m_u_component_of_wind,10m_v_component_of_wind,2m_specific_humidity,2m_temperature,surface_net_solar_radiation,thermal_surface_radiation_downwards,surface_pressure,total_precipitation
  - "RDRS_v2.1_P_TT_09944"                                     # RDRS variables | | RDRS_v2.1_P_FI_SFC,RDRS_v2.1_P_FB_SFC,RDRS_v2.1_A_PR0_SFC,RDRS_v2.1_P_P0_SFC,RDRS_v2.1_P_TT_1.5m,RDRS_v2.1_P_HU_1.5m,RDRS_v2.1_P_UVC_10m,RDRS_v2.1_P_UUC_10m
  - "RDRS_v2.1_P_UVC_09944"
  - "RDRS_v2.1_A_PR0_SFC"
  - "RDRS_v2.1_P_FB_SFC"
  - "RDRS_v2.1_P_FI_SFC"
FORCING_MEASUREMENT_HEIGHT: 3                                  # Reference height for forcing measurements [m].
FORCING_TIME_STEP_SIZE: 3600                                   # Size of the forcing time step in [s]. Must be constant.

# Data cleanup settings
UNIFY_SOIL: false                                              # Merge small soil areas
MINIMUM_LAND_FRACTION: 0.01                                    # Minimum land cover classification fraction to include
NUM_LAND_COVER: 20                                             # Number of land cover classes

# Other settings
LANDCOVER_YEAR: "2020"                                         # Year of land cover classification

## Model settings
HYDROLOGICAL_MODEL: SUMMA                                      # Hydrological model used, options: SUMMA, MESH (tbi), HYPE (tbi)
ROUTING_MODEL: mizuroute                                       # Routing model used, options: mizuroute, HEC-RAS (tbi)

# SUMMA settings
SETTINGS_SUMMA_PATH: default                                   # Path to SUMMA run settings
SETTINGS_SUMMA_FILEMANAGER: fileManager.txt                    # Name of SUMMA file manager
SETTINGS_SUMMA_FORCING_LIST: forcingFileList.txt               # Name of SUMMA forcing file list
SETTINGS_SUMMA_COLDSTATE: coldState.nc                         # Name of SUMMA initial conditions file
SETTINGS_SUMMA_TRIALPARAMS: trialParams.nc                     # Name of SUMMA trial parameters file
SETTINGS_SUMMA_ATTRIBUTES: attributes.nc                       # Nane of SUMMA attributes file
SETTINGS_SUMMA_CONNECT_HRUS: no                                # Attribute setting: "no" or "yes". If no; all HRUs modeled as independent columns 
SETTINGS_SUMMA_TRIALPARAM_N: 1                                 # Number of trial parameter specifications. Specify 0 if none are wanted (they can still be included in this file but won't be read).
SETTINGS_SUMMA_TRIALPARAM_1: maxstep,900                       # Name of trial parameter and value to assign. Value assumed to be float.
SUMMA_INSTALL_PATH: default                                    # SUMMA installation path
SUMMA_EXE: summa.exe                                           # Name of SUMMA executable


# Summaflow settings
SUMMAFLOW: spatial                                             # SUMMA setup paradigm, options: spatial or stochastic


# Mizuroute settings
SETTINGS_MIZU_TOPOLOGY: topology.nc                            # Name of the river network topology file.
SETTINGS_MIZU_PARAMETERS: param.nml.default                    # Mizuroute parameter file
SETTINGS_MIZU_CONTROL_FILE: mizuroute.control                  # Name of the control file.
SETTINGS_MIZU_REMAP: routing_remap.nc                          # Name of the optional catchment remapping file, for cases when SUMMA uses different catchments than mizuRoute.
SETTINGS_MIZU_WITHIN_BASIN: 0                                  # '0' (no) or '1' (IRF routing). Flag to enable within-basin routing by mizuRoute. Should be set to 0 if SUMMA is run with "subRouting" decision "timeDlay".
SETTINGS_MIZU_ROUTING_DT: 3600                                 # Duration of the routing time step [s].
SETTINGS_MIZU_ROUTING_UNITS: m/s                               # Units of the variable to be routed.
SETTINGS_MIZU_ROUTING_VAR: averageRoutedRunoff                 # Name of output variable to use for routing.
SETTINGS_MIZU_OUTPUT_FREQ: single                              # Frequency with which mizuRoute generates new output files. Must be one of 'single', 'daily', 'monthly', 'yearly'.
SETTINGS_MIZU_OUTPUT_VARS: 1                                   # Routing output. '0' for both KWT and IRF; '1' IRF only; '2' KWT only.
SETTINGS_MIZU_MAKE_OUTLET: n/a                                 # Segment ID or IDs that should be set as network outlet. Specify multiple IDs separated by commas: X,Y,Z. Specify no IDs as: n/a. Note that this can also be done in the network shapefile.
SETTINGS_MIZU_NEEDS_REMAP: no                                  # 'no' if routing basins map 1:1 onto model GRUs. 'yes' if river segments span multiple GRUs or if multiple segments are inside a single GRU.
SETTINGS_MIZU_PATH: default                                    # Directory containing mizuroute settings
INSTALL_PATH_MIZUROUTE: default                                # Mizuroute installation path
EXE_NAME_MIZUROUTE: mizuroute.exe                              # Name of mizuroute executable



# MESH settings
# HYPE settings

## Optimization settings
#Ostrich settings