CONFLUENCE_DATA_DIR: /anvil/scratch/x-deythorsson/CONFLUENCE_data
CONFLUENCE_CODE_DIR: /Users/darrieythorsson/compHydro/code/CONFLUENCE
DOMAIN_NAME: camelsspat_template
EXPERIMENT_ID: run_1
EXPERIMENT_TIME_START: 2005-01-01 01:00
EXPERIMENT_TIME_END: 2015-12-31 23:00
CALIBRATION_PERIOD: 1982-01-01, 1990-12-30
EVALUATION_PERIOD: 2012-01-01, 2023-12-30
SPINUP_PERIOD: 1980-01-02, 1981-12-31
MPI_PROCESSES: 1
FORCE_RUN_ALL_STEPS: false
POUR_POINT_COORDS: 51.1722/-115.5717
BOUNDING_BOX_COORDS: 51.76/-116.55/50.95/-115.5
DOMAIN_DEFINITION_METHOD: lumped
GEOFABRIC_TYPE: TDX
STREAM_THRESHOLD: 2500
CLEANUP_INTERMEDIATE_FILES: true
DELINEATE_BY_POURPOINT: true
MOVE_OUTLETS_MAX_DISTANCE: 200
MIN_GRU_SIZE: 0
DOMAIN_DISCRETIZATION: GRUs
ELEVATION_BAND_SIZE: 200
MIN_HRU_SIZE: 4
RADIATION_CLASS_NUMBER: 5
FORCING_DATASET: CASR
FORCING_VARIABLES: default
FORCING_MEASUREMENT_HEIGHT: 1.5
FORCING_TIME_STEP_SIZE: 3600
APPLY_LAPSE_RATE: true
LAPSE_RATE: 0.0065
FORCING_SHAPE_LAT_NAME: lat
FORCING_SHAPE_LON_NAME: lon
SUPPLEMENT_FORCING: false
EM_EARTH_PRCP_DIR: /anvil/datasets/meteorological/EM-Earth/EM_Earth_v1/deterministic_hourly/prcp/NorthAmerica
EM_EARTH_TMEAN_DIR: /anvil/datasets/meteorological/EM-Earth/EM_Earth_v1/deterministic_hourly/tmean/NorthAmerica
EM_EARTH_MIN_BBOX_SIZE: 0.1
EM_EARTH_MAX_EXPANSION: 0.2
HYDROLOGICAL_MODEL: SUMMA
ROUTING_MODEL: mizuRoute
SUMMA_EXE: summa_sundials.exe
SETTINGS_SUMMA_USE_PARALLEL_SUMMA: false
SETTINGS_SUMMA_PARALLEL_EXE: summa_actors.exe
SETTINGS_SUMMA_CONNECT_HRUS: true
SETTINGS_SUMMA_TRIALPARAM_N: 0
SETTINGS_SUMMA_TRIALPARAM_1: null
PARAMS_TO_CALIBRATE: tempCritRain,k_soil,vGn_n,theta_sat,theta_res,rootingDepth,zScale_TOPMODEL,k_macropore
BASIN_PARAMS_TO_CALIBRATE: routingGammaScale
SUMMA_DECISION_OPTIONS:
  snowIncept:
  - lightSnow
  compaction:
  - anderson
  snowLayers:
  - CLM_2010
  alb_method:
  - conDecay
  thCondSnow:
  - jrdn1991
  - smnv2000
  vegeParTbl:
  - MODIFIED_IGBP_MODIS_NOAH
  soilStress:
  - NoahType
  stomResist:
  - BallBerry
  LAI_method:
  - monTable
  veg_traits:
  - Raupach_BLM1994
  canopyEmis:
  - difTrans
  windPrfile:
  - logBelowCanopy
  canopySrad:
  - BeersLaw
  soilCatTbl:
  - ROSETTA
  f_Richards:
  - mixdform
  groundwatr:
  - bigBuckt
  hc_profile:
  - constant
  bcLowrSoiH:
  - drainage
  thCondSoil:
  - funcSoilWet
  spatial_gw:
  - localColumn
  subRouting:
  - timeDlay
  num_method:
  - itertive
  fDerivMeth:
  - analytic
  bcUpprTdyn:
  - nrg_flux
  bcLowrTdyn:
  - zeroFlux
  bcUpprSoiH:
  - liq_flux
  astability:
  - louisinv
CALIBRATE_DEPTH: false
DEPTH_TOTAL_MULT_BOUNDS:
- 0.1
- 5.0
DEPTH_SHAPE_FACTOR_BOUNDS:
- 0.1
- 3.0
FUSE_EXE: fuse.exe
FUSE_DECISION_OPTIONS:
  RFERR:
  - additive_e
  - multiplc_e
  ARCH1:
  - tension1_1
  ARCH2:
  - tens2pll_2
  QSURF:
  - arno_x_vic
  - prms_varnt
  QPERC:
  - perc_f2sat
  ESOIL:
  - sequential
  QINTF:
  - intflwnone
  Q_TDH:
  - rout_gamma
  SNOWM:
  - temp_index
  - no_snowmod
GR_EXE: GR.r
HYPE_EXE: hype
MESH_EXE: mesh.exe
FLASH_LOAD: false
FLASH_HIDDEN_SIZE: 128
FLASH_NUM_LAYERS: 3
FLASH_EPOCHS: 300
FLASH_BATCH_SIZE: 64
FLASH_LEARNING_RATE: 0.001
FLASH_LEARNING_PATIENCE: 30
FLASH_LOOKBACK: 700
FLASH_DROPOUT: 0.2
FLASH_L2_REGULARIZATION: 1e-6
FLASH_USE_ATTENTION: true
FLASH_USE_SNOW: false
EXE_NAME_MIZUROUTE: mizuroute.exe
SETTINGS_MIZU_WITHIN_BASIN: 0
SETTINGS_MIZU_ROUTING_DT: 3600
SETTINGS_MIZU_ROUTING_UNITS: m/s
SETTINGS_MIZU_ROUTING_VAR: averageRoutedRunoff
SETTINGS_MIZU_OUTPUT_FREQ: single
SETTINGS_MIZU_OUTPUT_VARS: 1
SETTINGS_MIZU_MAKE_OUTLET: n/a
SETTINGS_MIZU_NEEDS_REMAP: false
EVALUATION_DATA:
- streamflow
ANALYSES:
- benchmarking
SIM_REACH_ID: 123
STREAMFLOW_DATA_PROVIDER: WSC
DOWNLOAD_USGS_DATA: false
DOWNLOAD_WSC_DATA: true
STATION_ID: 05BB001
DOWNLOAD_SNOTEL: 'false'
SNOTEL_STATION: '602'
SNOTEL_PATH: /work/comphyd_lab/data/geospatial-data/SNOTEL
DOWNLOAD_FLUXNET: 'false'
FLUXNET_STATION: CA-NS7
FLUXNET_PATH: /work/comphyd_lab/data/geospatial-data/fluxnet
DOWNLOAD_USGS_GW: 'true'
USGS_STATION: '06306300'
OPTIMISATION_METHODS:
- iteration
- emulation
EMULATION_NUM_SAMPLES: 100
EMULATION_SEED: 22
EMULATION_SAMPLING_METHOD: lhs
EMULATION_PARALLEL_ENSEMBLE: false
EMULATION_MAX_PARALLEL_JOBS: 100
EMULATION_SKIP_MIZUROUTE: false
EMULATION_USE_ATTRIBUTES: false
EMULATION_MAX_ITERATIONS': 3
RUN_RANDOM_FOREST_EMULATION: false
RUN_NEURAL_NETWORK_EMULATION: true
EMULATION_TARGET_METRIC: KGE
EMULATOR_IMPROVEMENT_THRESHOLD: 0.01
ENABLE_GAP_FILLING: true
GAP_FILLING_SAMPLES: 50
GAP_FILLING_METHODS:
- density
- boundary
- uncertainty
- diversity
RUN_GAP_FILLING_SIMULATIONS: true
GAP_DENSITY_THRESHOLD: 0.1
GAP_BOUNDARY_MARGIN: 0.1
GAP_UNCERTAINTY_PERCENTILE: 90
NN_HIDDEN_LAYERS:
- 100
- 50
NN_MAX_ITERATIONS: 1000
NN_LEARNING_RATE: 0.001
NN_VALIDATION_SPLIT: 0.2
ITERATIVE_OPTIMIZATION_ALGORITHM: DE
NUMBER_OF_ITERATIONS: 100
POPULATION_SIZE: 30
OPTIMIZATION_METRIC: KGE
DE_SCALING_FACTOR: 0.5
DE_CROSSOVER_RATE: 0.9
DDS_R: 0.4
NUMBER_OF_COMPLEXES: 2
POINTS_PER_SUBCOMPLEX: 5
NUMBER_OF_EVOLUTION_STEPS: 20
EVOLUTION_STAGNATION: 5
PERCENT_CHANGE_THRESHOLD: 0.01
SWRMSIZE: 20
PSO_COGNITIVE_PARAM: 1.5
PSO_SOCIAL_PARAM: 1.5
PSO_INERTIA_WEIGHT: 0.7
PSO_INERTIA_REDUCTION_RATE: 0.99
CATCHMENT_SHP_LAT: center_lat
CATCHMENT_SHP_LON: center_lon
CATCHMENT_SHP_AREA: HRU_area
CATCHMENT_SHP_HRUID: HRU_ID
CATCHMENT_SHP_GRUID: GRU_ID
CATCHMENT_PATH: default
CATCHMENT_SHP_NAME: default
RIVER_BASIN_SHP_RM_GRUID: GRU_ID
RIVER_BASIN_SHP_HRU_TO_SEG: gru_to_seg
RIVER_BASIN_SHP_AREA: GRU_area
RIVER_BASINS_PATH: default
RIVER_BASINS_NAME: default
RIVER_NETWORK_SHP_LENGTH: Length
RIVER_NETWORK_SHP_SEGID: LINKNO
RIVER_NETWORK_SHP_DOWNSEGID: DSLINKNO
RIVER_NETWORK_SHP_SLOPE: Slope
RIVER_NETWORK_SHP_PATH: default
RIVER_NETWORK_SHP_NAME: default
POUR_POINT_SHP_PATH: default
POUR_POINT_SHP_NAME: default
FORCING_PATH: default
OBSERVATIONS_PATH: default
STREAMFLOW_RAW_PATH: default
STREAMFLOW_RAW_NAME: default
STREAMFLOW_PROCESSED_PATH: default
HYDAT_PATH: default
SIMULATIONS_PATH: default
ATTRIBUTES_DATA_DIR: /work/comphyd_lab/data/_to-be-moved/NorthAmerica_geospatial/
ATTRIBUTES_SOILGRIDS_PATH: default
ATTRIBUTES_PELLETIER_PATH: default
ATTRIBUTES_MERIT_PATH: default
ATTRIBUTES_MODIS_PATH: default
ATTRIBUTES_GLCLU_PATH: default
ATTRIBUTES_FOREST_HEIGHT_PATH: default
ATTRIBUTES_WORLDCLIM_PATH: default
ATTRIBUTES_GLIM_PATH: default
ATTRIBUTES_GROUNDWATER_PATH: default
ATTRIBUTES_STREAMFLOW_PATH: default
HRU_GAUGE_MAPPING: {}
ATTRIBUTES_GLWD_PATH: default
ATTRIBUTES_HYDROLAKES_PATH: default
ATTRIBUTES_OUTPUT_DIR: default
SETTINGS_HYPE_PATH: default
HYPE_INSTALL_PATH: default
SETTINGS_GR_PATH: default
SETTINGS_GR_CONTROL: default
GR_INSTALL_PATH: default
SETTINGS_FUSE_FILEMANAGER: default
SETTINGS_FUSE_PATH: default
FUSE_INSTALL_PATH: default
EXPERIMENT_OUTPUT_FUSE: default
SETTINGS_SUMMA_PATH: default
EXPERIMENT_OUTPUT_SUMMA: default
EXPERIMENT_LOG_SUMMA: default
SETTINGS_SUMMA_PARALLEL_PATH: default
SUMMA_INSTALL_PATH: default
SETTINGS_SUMMA_FILEMANAGER: fileManager.txt
SETTINGS_SUMMA_FORCING_LIST: forcingFileList.txt
SETTINGS_SUMMA_COLDSTATE: coldState.nc
SETTINGS_SUMMA_TRIALPARAMS: trialParams.nc
SETTINGS_SUMMA_ATTRIBUTES: attributes.nc
SETTINGS_SUMMA_OUTPUT: outputControl.txt
SETTINGS_SUMMA_BASIN_PARAMS_FILE: basinParamInfo.txt
SETTINGS_SUMMA_LOCAL_PARAMS_FILE: localParamInfo.txt
EXPERIMENT_LOG_MIZUROUTE: default
EXPERIMENT_OUTPUT_MIZUROUTE: default
SETTINGS_MIZU_PATH: default
INSTALL_PATH_MIZUROUTE: default
SETTINGS_MIZU_TOPOLOGY: topology.nc
SETTINGS_MIZU_PARAMETERS: param.nml.default
SETTINGS_MIZU_CONTROL_FILE: mizuroute.control
SETTINGS_MIZU_REMAP: routing_remap.nc
INTERSECT_SOIL_PATH: default
INTERSECT_SOIL_NAME: default
INTERSECT_ROUTING_PATH: default
INTERSECT_ROUTING_NAME: default
INTERSECT_DEM_PATH: default
INTERSECT_DEM_NAME: default
INTERSECT_LAND_PATH: default
INTERSECT_LAND_NAME: default
OUTPUT_BASINS_PATH: default
OUTPUT_RIVERS_PATH: default
DEM_PATH: default
DEM_NAME: default
SOURCE_GEOFABRIC_BASINS_PATH: default
SOURCE_GEOFABRIC_RIVERS_PATH: default
TAUDEM_DIR: default
OUTPUT_DIR: default
CATCHMENT_PLOT_DIR: default
SOIL_CLASS_PATH: default
SOIL_CLASS_NAME: default
LAND_CLASS_PATH: default
LAND_CLASS_NAME: default
RADIATION_PATH: default
DATATOOL_PATH: default
GISTOOL_PATH: default
EASYMORE_CLIENT: easymore cli
DATATOOL_DATASET_ROOT: /work/comphyd_lab/data/meteorological-data/
DATATOOL_CACHE: /home/darri.eythorsson
GISTOOL_DATASET_ROOT: /work/comphyd_lab/data/geospatial-data/
GISTOOL_LIB_PATH: /work/comphyd_lab/envs/r-env/
TOOL_CACHE: /home/darri.eythorsson/cache
EASYMORE_CACHE: /home/darri.eythorsson/easymore/
EASYMORE_JOB_CONF: installs/MAF/02_model_agnostic_component/easymore-job.slurm
CLUSTER_JSON: /work/comphyd_lab/users/darri/data/CONFLUENCE_data/installs/datatool/etc/clusters/ucalgary-arc.json
