name: confluence
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - numpy
  - pandas
  - geopandas
  - rasterio
  - netcdf4
  - pyyaml
  - shapely  
  - pip
  - pip:
    - rasterstats
